export const ADD_FCILITIES = "ADD_FCILITIES"
export const DELETE_FCILITIES = "DELETE_FCILITIES"
export const UPDATE_FCILITIES = "UPDATE_FCILITIES"
export const LOADING_FCILITIES = "LOADINGE_FCILITIES"
export const GET_FCILITIES = "GET_FCILITIES"


export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const LOADING_PRODUCT = "LOADINGE_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"

export const GET_SHOP = "GET_SHOP"

export const GET_SHOPDETAIL = "GET_SHOPDETAIL"
export const ADD_SHOPDETAIL = "ADD_SHOPDETAIL"
export const DELETE_SHOPDETAIL = "DELETE_SHOPDETAIL"
export const UPDATE_SHOPDETAIL = "UPDATE_SHOPDETAIL"
export const LOADING_SHOPDETAIL = "LOADINGE_SHOPDETAIL"
export const ERROR_SHOPDETAIL = "ERROR_SHOPDETAIL"

export const GET_REVIEW = "GET_REVIEW"
export const ADD_REVIEW = "ADD_REVIEW"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"
export const LOADING_REVIEW = "LOADINGE_REVIEW"
export const ERROR_REVIEW = "ERROR_REVIEW"

export const GET_CART = "GET_CART"

export const GET_CATEGORY = "GET_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"


export const LOADING_VARIANTS = "LOADING_VARIANTS"
export const ERROR_VARIANTS = "ERROR_VARIANTS"
export const GET_VARIANTS = "GET_VARIANTS"
export const ADD_VARIANTS = "ADD_VARIANTS"
export const DELETE_VARIANTS = "DELETE_VARIANTS"
export const EDIT_VARIANTS = "EDIT_VARIANTS"

export const GET_SALESPEOPLE = "GET_SALESPEOPLE"
export const ADD_SALESPEOPLE = "ADD_SALESPEOPLE"
export const DELETE_SALESPEOPLE = "DELETE_SALESPEOPLE"
export const EDIT_SALESPEOPLE = "EDIT_SALESPEOPLE"