
export const TOGGLE_THEME = "TOGGLE_THEME"

export const ADD_CHECKOUT = "ADD_CHECKOUT"
export const DELETE_CHECKOUT = "DELETE_CHECKOUT"
export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT"
export const GET_CHECKOUT = "GET_CHECKOUT"


export const ADD_CONTACT = "ADD_CONTACT"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const UPDATE_CONTACT = "UPDATE_CONTACT"
export const GET_CONTACT = "GET_CONTACT"
